export const WS_EVENTS = {
  AUTH: 'AUTH',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  ROOM_JOIN: 'ROOM_JOIN',
  ROOM_JOINED: 'ROOM_JOINED',
  USER_JOINED: 'USER_JOINED',
  USER_LEFT: 'USER_LEFT',
  ROOM_PRESENCE: 'ROOM_PRESENCE',
  PING: 'PING',
  PONG: 'PONG',
  ERROR: 'ERROR'
};
